### ISSUE TITLE
Nodejs Pouchdb vs Browser Pouchdb 

### ISSUE THREAD

**Issue by agozie** [nolanlawson/pouchdb-electron#1]
I easily got pouchdb working with leveldb adapter in Electron. Is it not better than using IndexDb and WebSql where there are storage limitations? Are there disadvantages to this approach besides compiling levelDown for Electron?

**Comment by nolanlawson** [comment]
I think the only advantages/disadvantages would be in performance, and I haven't tested Electron to see which of the three is the fastest. Electron _might_ apply Chrome's heuristics to trim IndexedDB/WebSQL size if the system comes under heavy load (i.e. the user is running out of disk space), but you'd have to ask the Electron developers to see if that's the case.

BTW if you managed to compiled leveldown for Electron it would be awesome to open a PR on the readme explaining how you did it. :) I tried to do it a couple times and failed each time.

**Comment by nolanlawson** [comment]
Forgot to mention: my hunch is that LevelDB is the fastest, then WebSQL, then IndexedDB, but that's purely a hunch. :)

**Comment by nolanlawson** [comment]
FWIW, I found this topic about building leveldown for Electron. Seems it's not working yet? https://github.com/Level/electron-demo/issues/1

**Comment by agozie** [comment]
I used the second option here https://github.com/atom/electron/blob/master/docs/tutorial/using-native-node-modules.md

**Comment by nolanlawson** [comment]
And it's working? That's very interesting. cc @juliangruber

**Comment by juliangruber** [comment]
awesome, thanks @agozie @nolanlawson!

**Comment by nolanlawson** [comment]
I'm going to document this in the README.
