### ISSUE TITLE
With LevelDB

### ISSUE THREAD

**Issue by khanetor** [nolanlawson/pouchdb-electron#3]
In this guide you use IndexedDB and WebSQL. How about LevelDB?

**Comment by nolanlawson** [comment]
Some people have had some success. I'll add a note to the README: https://github.com/nolanlawson/pouchdb-electron/issues/1#issuecomment-132310987

**Comment by nolanlawson** [comment]
OK, see the working code at https://github.com/nolanlawson/hello-electron-with-pouchdb
