### ISSUE TITLE
Use indexdb/websql without importing pouchdb as global.

### ISSUE THREAD

**Issue by blmarket** [nolanlawson/pouchdb-electron#5]
instead of using `<script ...>`, I found `require` is also working. hope this is helpful to those who don't want to add global module declarations.

```
const PouchDB = require('pouchdb/dist/pouchdb');
// use as Node.js module... with more adapters
```

**Comment by nolanlawson** [comment]
Yeah, another way to do it is to use our modern "custom builders" setup and `require('pouchdb-browser')`.

I'd accept a PR to update it to use the more modern format.
