### ISSUE TITLE
Can't build leveldb on electron compile

### ISSUE THREAD

**Issue by woomike** [nolanlawson/pouchdb-electron#7]
The `postinstall.sh` script and PouchDB work if I'm running my electron app locally, but if I compile my app for production / distribution PouchDB no longer works and returns `undefined`.  

Is there a proper way to bundle the levelDB portion when compiling the electron app?  I need to use PouchDB on the Node.js side, so pouchdb-browser is not an option.

**Comment by quinnmcphail** [comment]
I am also experiencing this same problem. I run `electron .` and PouchDB works flawlessly. After I run `electron-builder`, `electron-packager`, or manually package my app, PouchDB returns `undefined`.

**Comment by rusintez** [comment]
try level-js, eg.

```javascript
var PouchDB = require('pouchdb');
var level   = require('level-js');

var db = new PouchDB('test', { db: level });

db.put({
  _id: 'dave@gmail.com',
  name: 'David',
  age: 69
});

db.changes().on('change', function() {
  console.log('Ch-Ch-Changes');
});
```

**Comment by rusintez** [comment]
and don't use `yarn` for builds if possible

**Comment by seales** [comment]
The optional attribute `db` is now deprecated, with PouchDB v6.1.1: https://github.com/pouchdb/pouchdb/releases/tag/6.1.1

**Comment by nolanlawson** [comment]
Check out https://github.com/nolanlawson/hello-electron-with-pouchdb . I'm using `electron-rebuild` now so everything should be working.
