### ISSUE TITLE
IO Error with electron-packager after electron-rebuild

### ISSUE THREAD

**Issue by BrunoBernardino** [nolanlawson/pouchdb-electron#9]
Before I start, this is my first Electron app, and I've built this app I'll show in a very short amount of time, so it's very likely I'm missing something.

That being said, I've been banging my head against this and can't understand the problem.

The app is at https://github.com/BrunoBernardino/Oikon2-Mac

The "initialization" is in [`utils/DataDB.js`](https://github.com/BrunoBernardino/Oikon2-Mac/blob/master/utils/DataDB.js#L17).

I have the `IO Error` described in https://github.com/pouchdb/pouchdb/issues/4514 and I've implemented `electron-rebuild` to fix that while developing (`npm start`).

<img width="574" alt="screen shot 2017-05-22 at 22 06 58" src="https://cloud.githubusercontent.com/assets/1239616/26328661/e3d7f1a8-3f3b-11e7-820b-ee354961f804.png">

However, when I `npm run build` and open the app, I can see in the console that same error.

I'm using the `afterCopy` hook for the `electron-rebuild` in [`build.js`](https://github.com/BrunoBernardino/Oikon2-Mac/blob/master/build.js), as per [the documentation](https://github.com/electron/electron-rebuild/#how-can-i-integrate-this-into-electron-packager).

I've tried using other adapters as seen in https://github.com/nolanlawson/hello-electron-with-pouchdb and all also failed, giving some variation of the same error (can't open file).

Permissions appear to be fine, and I've tried building for `darwin` and `mas` with the same results.

I'm suspecting it's somehow trying to look for the files somewhere else once packaged, but I can't see why/how.

Please tell me there's something obvious I'm doing wrong 😄 .

**Comment by BrunoBernardino** [comment]
@nolanlawson Any thoughts on this one?

**Comment by nolanlawson** [comment]
I think you need to `mkdir` the directory before you can use a LevelDB database inside. The npm `mkdirp` package should work well.

**Comment by BrunoBernardino** [comment]
Thank you for that! The directory exists, with the `LOCK` file. Unless it's trying to look somewhere else, which would be strange, since other `require()`s in the same file appear to be working just fine. Any idea where it would be looking for that, if not inside `Contents/Resources/app/*` ?

**Comment by nolanlawson** [comment]
Sorry, I really don't know. :confused: I wrote this tutorial a long time ago and it feels like electron changes something every few months and it breaks. If you figure something out, please feel free to open a PR! 🙂

**Comment by BrunoBernardino** [comment]
I fixed it by "forcing" the directory (somewhere it wasn't being set properly, _after_ packaging): https://github.com/BrunoBernardino/Oikon2-Mac/pull/2/files#diff-0aa32d546cef508ec48190878d4d7f50R17
